enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# modified by lavinhoque33, 2026-10-07: build from the lavinhoque33 fork of anddea's patches.
patches-source = "lavinhoque33/revanced-patches"
patches-version = "latest"

cli-source = "MorpheApp/morphe-cli"
cli-version = "latest"

rv-brand = "ReVanced Extended"

enable-update-checks = true

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "21.39.525"
# modified by lavinhoque33, 2026-10-07: 21.39.525 is only published for arm64-v8a.
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom header for YouTube'"
included-patches = "'Visual preferences icons for YouTube' 'Return YouTube Username'"
patcher-args = "-e 'Custom branding name for YouTube' -OappName='YouTube RVX' -e 'Custom branding icon for YouTube' -OappIcon='vanced_black' -e 'Theme' -OlightThemeBackgroundColor=#FFF9F9F9"

# https://github.com/j-hc/revanced-magisk-module/issues/554
[YouTube-Music-RVX]
app-name = "YouTube Music"
build-mode = "both"
arch = "both"
# modified by lavinhoque33, 2026-10-07: 9.40.51 (auto-updated from the patches fork's supported versions).
version = "9.40.51"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Custom header for YouTube Music'"
included-patches = "'Visual preferences icons for YouTube Music' 'Return YouTube Username' 'Disable music video in album'"
patcher-args = "-e 'Custom branding name for YouTube Music' -OappName='YT Music RVX' -e 'Custom branding icon for YouTube Music' -OappIcon='vanced_black'"
